version: "3"
services:
    nginx:
        build: ./nginx
        image: bahon/nginx:0.1.0
        restart: always
        ports:
            - "80:80"
        depends_on:
            - web

    web:
        build: ./web
        image: bahon/web:0.1.0
        restart: always
        # more than 1 worker messes up sqlite3 and causes
        # sqlite3.OperationalError: database is locked
        command: gunicorn -w 1 -b 0.0.0.0:8000 run:app
        expose:
            - "8000"
